### ISSUE TITLE
Develop home page

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/rocc#11]
Develop a home page for the challenge registry.

Tasks:

- [x] - Create a wire frame of the page
- [x] - Collect and integrate feedback
- [x] - Identify the data required to render the page
- [x] - Update the API service and client to get access to the data required
- [x] - Develop the home page

**Comment by vpchung** [comment]
Version 1 of the wireframe [here](https://www.figma.com/file/3FhUN0TM2IZppl34eEjeXT/Landing-Page).

I will be collecting feedback at the upcoming project sync next Wednesday or async via Figma comments.

**Comment by vpchung** [comment]
Related: #33
